#!/bin/bash

FSTART="false"
input="./NeoGeoAES-3.5-Nightly/libs/1_NeoGeoLibrary.pretty"
output="./NeoGeoAES-3.5/libs/1_NeoGeoLibrary.pretty"

do_ () {
  rm $2
  while IFS= read -r LINE
  do
    if [[ "$LINE" == *"version"* ]]; then
	TT=`echo "$LINE" | sed 's/version ......../version 20211014/'`
        echo "$TT" >> $2
    elif [[ "$LINE" == *"(fp_"* ]]; then
        FLINE="$LINE"
        read -r LINE
        if [[ "$LINE" == *"(stroke"* ]]; then
          TT=`echo "$LINE" | sed 's/^.*(stroke//' | sed 's/(type solid)//' | sed 's/(type default)//' | sed 's/) ) (/) (/' | sed 's/ (width/(width/'`
          echo "$FLINE $TT" >> $2
        else
          echo "$FLINE" >> $2
          echo "    $LINE" >> $2
        fi
    elif [[ "$LINE" == *"(pad"* ]]; then
        FLINE="$LINE"
        read -r LINE
        if [[ "$LINE" == *"(tstamp"* ]]; then
          if [[ "$LINE" == *"(thermal_bridge_angle"* ]]; then
            TT=`echo "$LINE" | sed 's/(thermal_bridge_angle.*) (/(/'`
            echo "$FLINE $TT" >> $2
          else
            echo "$FLINE" >> $2
            echo "    $LINE" >> $2
          fi
        elif [[ "$LINE" == *"(thermal_bridge_angle"* ]]; then
           echo "$FLINE" >> $2
        else
           echo "$FLINE" >> $2
           echo "    $LINE" >> $2
        fi
    else
      echo "$LINE" >> $2
    fi
  done < "$1"
}

for f in $input/*.kicad_mod; 
do
  if [[ "$f" != *"/_"* ]]; then
    FN=`basename "$f"`
    echo "Processing $f file..."
    do_ $f "$output/$FN"
  fi
done


