#!/bin/bash


do_sch () {
  echo "FILE $f" >> $output
  while IFS= read -r LINE
  do
  
    if [[ "$LINE" == "  (symbol "* ]]; then
      FSTART="true"
      FREF=""
      FFOOTREF=""
    fi

    if [ "$FSTART" == "true" ]; then
      if [[ "$LINE" == "  )" ]]; then
        FSTART="false"
        if [ "$FFOOTREF" != "" ]; then
           NEWF=`./findpcbfootprint "$FREF"`
           if [ "$NEWF" != "$FFOOTREF" ]; then
             echo "$FREF $FFOOTREF $NEWF"
             echo "$FREF $FFOOTREF $NEWF" >> $output
           fi
        fi
      fi
    fi

    if [ "$FSTART" == "true" ]; then
      if [[ "$LINE" == *"(property \"Reference\""* ]]; then
        FREF=`echo "$LINE" | awk '{print $3}'`
      fi

      if [[ "$LINE" == *"(property \"Footprint\""* ]]; then
        FFOOTREF=`echo "$LINE" | awk '{print $3}'`
        if [ "$FFOOTREF" == "\"\"" ]; then
          FFOOTREF=""
        fi
      fi
    fi
  done < "$1"
}


FSTART="false"
input="./NeoGeoAES-3.5/sheets/video.kicad_sch"
output="./schematic_reference.txt"
rm $output

for f in ./NeoGeoAES-3.5/sheets/*.kicad_sch; 
do
  if [[ "$f" != *"/_"* ]]; then
    echo "Processing $f file..."
    do_sch $f
  fi
done


