#!/bin/bash

FSTART="false"
main="./NeoGeoAES-3.5/NeoGeoAES3_5.kicad_sch"
input="./NeoGeoAES-3.5/sheets"
output="./tmp"
mkdir -p $output

writeme () {
   echo "$1" >> $2
}

updatemain () {
  cat $main | sed -E "s/(reference $1.*footprint )\".*\"(\))/\1$2\2/" > $output/main.kicad_sch
  if [ -s $output/main.kicad_sch ]; then
     cp -f $output/main.kicad_sch $main
  else
     echo "FILE IS EMPTY!!!"
     exit 0
  fi
}

do_sch () {
  echo "Processing $1 file..."
  rm "$2"
  while IFS= read -r LINE
  do  
    if [[ "$LINE" == "  (symbol "* ]]; then
      FSTART="true"
      FREF=""
      FFOOTREF=""
    fi

    if [ "$FSTART" == "true" ]; then
      if [[ "$LINE" == "  )" ]]; then
        FSTART="false"
      fi
    fi

    if [ "$FSTART" == "true" ]; then
      if [[ "$LINE" == *"(property \"Reference\""* ]]; then
        FREF=`echo "$LINE" | awk '{print $3}'`
        writeme "$LINE" $2
      elif [[ "$LINE" == *"(property \"Footprint\""* ]]; then
        FFOOTREF=`echo "$LINE" | awk '{print $3}'`
        if [ "$FFOOTREF" != "\"\"" ]; then
           echo "Searching For... $FREF"
           NEWF=`./findpcbfootprint "$FREF"`
           if [ "$NEWF" != "$FFOOTREF" ]; then
             echo "   Replace $FFOOTREF with $NEWF"
             RP=`echo "$LINE" | sed "s/$FFOOTREF/$NEWF/"`
             echo "$RP"
             writeme "$RP" $2
             updatemain "$FREF" "$NEWF"
           else
             writeme "$LINE" $2
           fi
        else
           writeme "$LINE" $2
        fi
      else
        writeme "$LINE" $2
      fi
    else
      writeme "$LINE" $2
    fi
  done < "$1"
  echo "Processing $1 file...Done"
  echo ""
  cp $2 $1
}

for f in $input/*.kicad_sch; 
do
  if [[ "$f" != *"/_"* ]]; then
    FN=`basename "$f"`
    do_sch "$f" "$output/$FN"
  fi
done
